### PR TITLE
Adapt with util/mongoapi changes

### PR DESCRIPTION
**Pull request by gatici**
- Use util library v1.0.12 to get latest mongoapi changes
- Adapt to the mongoapi changes

### CODE REVIEW

**Comment by gatici** [comment]
This patch is  passed E2E integration test. https://canonical-charmed-5g.readthedocs-hosted.com/en/latest/tutorials/getting_started/ is used to test the patch.

**Comment by gatici** [comment]
> This patch is passed E2E integration test. https://canonical-charmed-5g.readthedocs-hosted.com/en/latest/tutorials/getting_started/ is used to test the patch.

```
gatici@gaticipc:~$ kubectl describe pod nrf-0 -n core
Name:             nrf-0
Namespace:        core
Priority:         0
Service Account:  nrf
Node:             gaticipc/192.168.1.133
Start Time:       Thu, 01 Feb 2024 13:59:44 +0300
Labels:           app.kubernetes.io/name=nrf
                  controller-revision-hash=nrf-5d5f579c46
                  statefulset.kubernetes.io/pod-name=nrf-0
Annotations:      cni.projectcalico.org/containerID: daddc073f1fe5ecf028acd36e361cd39a6a61ce05b6002ea71c8d0dfa6bfd17a
                  cni.projectcalico.org/podIP: 10.1.146.17/32
                  cni.projectcalico.org/podIPs: 10.1.146.17/32
                  controller.juju.is/id: b2c41466-ea4f-4fc2-8f90-9cddb5ca0e12
                  juju.is/version: 3.1.7
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "k8s-pod-network",
                        "ips": [
                            "10.1.146.17"
                        ],
                        "default": true,
                        "dns": {}
                    }]
                  k8s.v1.cni.cncf.io/networks-status:
                    [{
                        "name": "k8s-pod-network",
                        "ips": [
                            "10.1.146.17"
                        ],
                        "default": true,
                        "dns": {}
                    }]
                  model.juju.is/id: f2b23ab7-2c6a-46b4-8ab5-0c64602be2f4
                  unit.juju.is/id: nrf/0
Status:           Running
IP:               10.1.146.17
IPs:
  IP:           10.1.146.17
Controlled By:  StatefulSet/nrf
Init Containers:
  charm-init:
    Container ID:  containerd://06dd71eeae5ea9c77de8431071d34656c96a3dacc3539a1fc1ace0524f5f3317
    Image:         jujusolutions/jujud-operator:3.1.7
    Image ID:      docker.io/jujusolutions/jujud-operator@sha256:3a8eea67ea85427b77246f118fe0a669acceefad587f041925b92c1dd71fbca4
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/containeragent
    Args:
      init
      --containeragent-pebble-dir
      /containeragent/pebble
      --charm-modified-version
      1
      --data-dir
      /var/lib/juju
      --bin-dir
      /charm/bin
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 01 Feb 2024 13:59:45 +0300
      Finished:     Thu, 01 Feb 2024 13:59:45 +0300
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      nrf-application-config  Secret  Optional: false
    Environment:
      JUJU_CONTAINER_NAMES:  nrf
      JUJU_K8S_POD_NAME:     nrf-0 (v1:metadata.name)
      JUJU_K8S_POD_UUID:      (v1:metadata.uid)
    Mounts:
      /charm/bin from charm-data (rw,path="charm/bin")
      /charm/containers from charm-data (rw,path="charm/containers")
      /containeragent/pebble from charm-data (rw,path="containeragent/pebble")
      /var/lib/juju from charm-data (rw,path="var/lib/juju")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wjkt5 (ro)
Containers:
  charm:
    Container ID:  containerd://4cb6a74c7d3f59435072035cc17ae824ba42b634c5ec846f6767a46f8a4536aa
    Image:         jujusolutions/charm-base:ubuntu-22.04
    Image ID:      docker.io/jujusolutions/charm-base@sha256:eabcd2babd0d6162dd4421079819bd7b2721a462df8c2e4c0060e854234f8d80
    Port:          <none>
    Host Port:     <none>
    Command:
      /charm/bin/pebble
    Args:
      run
      --http
      :38812
      --verbose
    State:          Running
      Started:      Thu, 01 Feb 2024 13:59:46 +0300
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:38812/v1/health%3Flevel=alive delay=30s timeout=1s period=5s #success=1 #failure=1
    Readiness:      http-get http://:38812/v1/health%3Flevel=ready delay=30s timeout=1s period=5s #success=1 #failure=1
    Startup:        http-get http://:38812/v1/health%3Flevel=alive delay=30s timeout=1s period=5s #success=1 #failure=1
    Environment:
      JUJU_CONTAINER_NAMES:  nrf
      HTTP_PROBE_PORT:       3856
    Mounts:
      /charm/bin from charm-data (ro,path="charm/bin")
      /charm/containers from charm-data (rw,path="charm/containers")
      /var/lib/juju from charm-data (rw,path="var/lib/juju")
      /var/lib/juju/storage/certs/0 from nrf-certs-8e44c3aa (rw)
      /var/lib/juju/storage/config/0 from nrf-config-8e44c3aa (rw)
      /var/lib/pebble/default from charm-data (rw,path="containeragent/pebble")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wjkt5 (ro)
  nrf:
    Container ID:  containerd://ba62aa9d71f8902969d94892db34bc6a66613a25653302c098ecd5a699effab5
    Image:         gatici/sdcore-nrf:1.5
    Image ID:      docker.io/gatici/sdcore-nrf@sha256:19753d170372275b9c16764aa01524acda891df6c4c163eb07413562fa92f618
    Port:          <none>
    Host Port:     <none>
    Command:
      /charm/bin/pebble
    Args:
      run
      --create-dirs
      --hold
      --http
      :38813
      --verbose
    State:          Running
      Started:      Thu, 01 Feb 2024 13:59:46 +0300
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:38813/v1/health%3Flevel=alive delay=30s timeout=1s period=5s #success=1 #failure=1
    Readiness:      http-get http://:38813/v1/health%3Flevel=ready delay=30s timeout=1s period=5s #success=1 #failure=1
    Environment:
      JUJU_CONTAINER_NAME:  nrf
      PEBBLE_SOCKET:        /charm/container/pebble.socket
    Mounts:
      /charm/bin/pebble from charm-data (ro,path="charm/bin/pebble")
      /charm/container from charm-data (rw,path="charm/containers/nrf")
      /etc/nrf/ from nrf-config-8e44c3aa (rw)
      /support/TLS from nrf-certs-8e44c3aa (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wjkt5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  nrf-certs-8e44c3aa:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nrf-certs-8e44c3aa-nrf-0
    ReadOnly:   false
  nrf-config-8e44c3aa:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nrf-config-8e44c3aa-nrf-0
    ReadOnly:   false
  charm-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-wjkt5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/arch=amd64
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
gatici@gaticipc:~$ juju run gnbsim/leader start-simulation
Running operation 7 with 1 task
  - task 8 on unit-gnbsim-0

Waiting for task 8...
info: run juju debug-log to get more information.
success: "true"

```

**Review by gab-arrobo — APPROVED** [review]
+1 (tested changes with AiaB)

**Comment by gab-arrobo** [comment]
@gatici, in your UDR PR-53, you are replacing MongoDBLibrary with util/mongoapi. Would it be possible you do the same in this repo. I see that only `service/init.go` imports a logger from the `MongoDBLibrary` and this is the only reason why that module is used/imported in this repo. Is this something you can help address? Thanks!

**Comment by gatici** [comment]
> @gatici, in your UDR PR-53, you are replacing MongoDBLibrary with util/mongoapi. Would it be possible you do the same in this repo. I see that only `service/init.go` imports a logger from the `MongoDBLibrary` and this is the only reason why that module is used/imported in this repo. Is this something you can help address? Thanks!

Sure, I will create another PR for it. Thank you!

**Pull request merged**
