### PR TITLE
Fixes CI to run unit tests

### PR DESCRIPTION
**Pull request by gruyaume**
## Description

This PR fixes the existing CI workflow to run unit tests recursively and addresses various problems identified by `go test`

### CODE REVIEW

**Comment by gab-arrobo** [comment]
Can you also please update the dependabot extension to `yml` as part of this PR?

**Comment by gruyaume** [comment]
> Can you also please update the dependabot extension to `yml` as part of this PR?

Done

**Comment by gab-arrobo** [comment]
> > Can you also please update the dependabot extension to `yml` as part of this PR?
> 
> Done

Thanks!

**Comment by gab-arrobo** [comment]
@gruyaume, why are the changes in `nrfcache/nrf_cache_test.go` needed? The `unit-tests` passes in my setup without having to make the changes in `nrfcache/nrf_cache_test.go`.

**Comment by gruyaume** [comment]
> @gruyaume, why are the changes in `nrfcache/nrf_cache_test.go` needed? The `unit-tests` passes in my setup without having to make the changes in `nrfcache/nrf_cache_test.go`.

My bad, these were an artefact from testing (because they have sleeps in them and take a while to run). I re-added them.

**Comment by gruyaume** [comment]
> > > @gruyaume, why are the changes in `nrfcache/nrf_cache_test.go` needed? The `unit-tests` passes in my setup without having to make the changes in `nrfcache/nrf_cache_test.go`.
> > 
> > 
> > My bad, these were an artefact from testing (because they have sleeps in them and take a while to run). I re-added them.
> 
> Do you still need to make the import order change in `nrfcache/nrf_cache_test.go`? I am asking this because in my local setup, I can successfully run the unit tests without having to make any change in `nrfcache/nrf_cache_test.go`

Indeed, this change is not "needed", it's a linting improvement. I can remove it from this PR if you prefer.

**Review by gab-arrobo — APPROVED** [review]
+1 (tested changes locally)

**Pull request merged**
